  # Project information
site_name: vMenu Documentation
repo_url: https://github.com/vMenuRevampedTeam/vMenu
repo_name: vMenuRevampedTeam/vMenu
copyright: Copyright &copy; Tom Grobbe  

# Theme
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/solid/terminal
    repo: fontawesome/brands/github
  font: 
    code: Quicksand
    text: Quicksand
  features:
    - navigation.top
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.tooltips
    - search.share
    - search.suggest

  plugins:
  - typeset
  - search
  - optimize
  - git-committers:
      enabled: true
      repository: vMenuRevampedTeam/vMenu
      branch: revamped
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: false    

  palette:
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Why are you trying to burn your eyes?!

# Additional CSS
extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

hooks:
  - docs/.hooks/badges.py  

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.details
  - md_in_html
  - markdown.extensions.md_in_html:
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote      

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vespura-s-coding-paradise-285424882534187008
    - icon: material/patreon
      link: https://www.patreon.com/vespura
    - icon: material/github
      link: https://github.com/TomGrobbe  
    - icon: material/email
      link: mailto:contact@vespura.com    
